### ISSUE TITLE
Add test matrix for python versions and test 3.10

### ISSUE THREAD

**Issue by phlax** [envoyproxy/pytooling#299]
We need to test python 3.10 so it would be good to have a matrix setup to facilitate this (if its not there already)

We also need to consider whether we only target 3.10+ moving forward - i think yes

The implications of this are that if we go full 3.10 we can use newer language and libs, whereas if we dont we wil only have to ensure compatibility

The other implication is re users and testing

If we go strict 3.10+ we dont need to maintain a test matrix for different versions going forward

However, it also means we mandate to devs that use the tooling that they must use the correct python version

This will be a lot simpler once rules_python has proper toolchain/runtime env support

**Comment by phlax** [comment]
cc @htuch @moderation @kfaseela

**Comment by phlax** [comment]
re this - i think we need to pick-a-version for hashing/dependabot reasons also - some libs are/not required with certain versions so the pipsets defined in envoy will/not work accordingly

**Comment by htuch** [comment]
My vote would be just to bump to a fix known version. There is precedence for this in the dev experience, e.g. how we treat Bazel (pin and support a single version).

**Comment by htuch** [comment]
The only caveat is distros, it could be worth checking with Red Hat folks etc. 
@oschaaf

**Comment by oschaaf** [comment]
Thanks for tagging me @htuch. Right now we are using python 3.6, but I learned we may be able to use newer versions as well. I'm working to get a clear answer on this so I can articulate our requirements around this and relay them here.
